### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by WienerGames** [maicki/react-native-mask#4]
"react-native": "^0.55.4"
"react-native-mask": "^0.5.0"

FYI:  Significant slowing down of our app occurred when applying this mask inside a ScrollView. We basically had to abandon the library and use an alternative approach. The problem was most evident on iphone 6s plus.

**Comment by maicki** [comment]
Hey @WienerGames did you profile what was causing the slow down? Layout or rendering etc?

**Comment by maicki** [comment]
@WienerGames Could you be able to use Instruments and see what is causing the slow down? Still would be pretty curious about this. Thanks!

**Comment by WienerGames** [comment]
Sorry, can't do that for various reasons. Just read my previous post again to get an idea of how to reproduce the issue and then analyse it yourself. It's the better way. Good luck!

**Comment by maicki** [comment]
@WienerGames Thanks for your feedback.
